app_club_ff/urls.py
from django.conf import settings
from django.urls import path
from . import views

from django.shortcuts import render
from my_modules.base_views import DBAction, DBRead
from django.views.generic import TemplateView
from my_modules.database import MySql
from django.http import HttpResponse
import json

app_name = "app_club_ff"

urlpatterns = [
    path("index/", views.Index.as_view(), name="index"),
    path("fest_registration_page/",views.FestRegistrationPage.as_view(login_required=True), name="fest_registration_page"),
    path("fest_registration/", views.FestRegistration.as_view(login_required=True), name="fest_registration"),
    path("get_club_names/", views.get_club_names, name="get_club_names"),
    path("get_cff_years/", views.get_cff_years, name="get_cff_years"),
    path("get_filtered_cff/<club_name>/<year>", views.get_filtered_cff, name="get_filtered_cff"),
    path("fest_feed_page/", views.FestFeed.as_view(), name="fest_feed_page"),
    path("post_processor/<club_id>/<criteria>/<offset>/", views.PostProcessor.as_view(), name="post_processor"),
    path("archive_cff_booths_page/", views.ArchiveCffBooths.as_view(), name="archive_cff_booths_page"),
]

app_cse_ps/urls.py
from django.conf import settings
from django.urls import path
from . import views

LOGIN_REQUIRED = True

app_name = "app_cse_ps"

urlpatterns = [
    path("index/", views.Index.as_view(), name="index"),
    path("project_registration_page/",views.ProjectRegistrationPage.as_view(login_required=True), name="project_registration_page"),
    path("project_registration/",views.ProjectRegistration.as_view(login_required=True), name="project_registration"),
    path("course_list_page/", views.CourseListPage.as_view(), name="course_list_page"),
    path("booth_list_page/<course_code>", views.BoothListPage.as_view(), name="booth_list_page"),
    path("get_course_names/", views.get_course_names, name="get_course_names"),
    path("get_sections/<course_code>", views.get_sections, name="get_sections"),
    path("get_student/<student_id>", views.get_student, name="get_student"),
    path("archieve_projects/", views.ArchiveProjects.as_view(), name="archieve_projects"),
    path("get_trimesters/", views.get_trimesters, name="get_trimesters"),
    path("get_filtered_archeive_projects/<course_code>/<trimester>", views.get_filtered_archeive_projects, name="get_filtered_archeive_projects"),
    path("project_booth_page/<project_id>/", views.ProjectBoothPage.as_view(), name="project_booth_page"),    
    path("comment_loader/<project_id>/<already_loaded>/", views.CommentLoader.as_view(), name="comment_loader"),
    path("commenter/", views.Commenter.as_view(login_required=True), name="commenter"),
]

app_general/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "app_general"

urlpatterns = [
    path("index/", views.Index.as_view(), name="index"),
    path("student_registration_page/", views.StudentRegistrationPage.as_view(logout_required=True), name="student_registration_page"),
    path("student_registration/", views.StudentRegistration.as_view(), name="student_registration"),
    path("login_page/", views.LoginPage.as_view(logout_required=True), name="login_page"),
    path("login/", views.Login.as_view(logout_required=True), name="login"),
    path("logout/", views.Logout.as_view(login_required=True), name="logout"),
    path("teacher_dashboard_page/", views.TeacherDashboardPage.as_view(login_required=True), name="teacher_dashboard_page"),
    path("student_dashboard_page/", views.StudentDashboardPage.as_view(login_required=True), name="student_dashboard_page"),
    path("project_processor_teacher/<project_status>/", views.ProjectProcessorTeacher.as_view(login_required=True), name="project_processor_teacher"),
    path("project_processor/<project_status>/", views.ProjectProcessor.as_view(login_required=True), name="project_processor"),
    path("project_details_page/<project_id>/", views.ProjectDetailsPage.as_view(), name="project_details_page"),
    path("project_approve/<project_id>/", views.ProjectApprove.as_view(), name="project_approve"),
    path("booth_setup_page/<project_id>/",views.BoothSetupPage.as_view(), name="booth_setup_page"),
    path("booth_setup/",views.BoothSetup.as_view(), name="booth_setup"),
    # path("test_page/", views.TestPage.as_view(), name="test_page"),
    path("test_page/", views.TestPage.as_view(), name="test_page"),
    path("test/<len>/", views.Test.as_view(), name="test"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uiu_emas/urls.py
from django.contrib import admin
from django.urls import path, include
from app_cse_ps import urls as app_cse_ps_urls
from app_club_ff import urls as app_club_ff_urls
from app_admin import urls as app_admin_urls
from app_general import urls as app_general_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(app_admin_urls)),
    path('admin_django/', admin.site.urls),
    path('cse_ps/', include(app_cse_ps_urls), name="cse_ps"),
    path('club_ff/', include(app_club_ff_urls), name="club_ff"),
    path('general/', include(app_general_urls), name="general"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_general/models.py
from django.db import models

# Create your models here.

app_general/views.py
from django.shortcuts import render, redirect
from my_modules.base_views import DBAction, DBRead
from django.views.generic import TemplateView
from my_modules.database import MySql
from django.core.files.storage import FileSystemStorage
from datetime import datetime, timedelta
import hashlib

# Create your views here.

class TestPage(DBRead):
    template_name = "app_general/test_page.html"

    def get_context_data(self, request, *args, **kwargs):
        return {
            "user": "student"
        }


class Test(DBRead):

    template_name = "app_general/test.html"

    def get_context_data(self, request, *args, **kwargs):
        context = {}
        context["len"] = [l for l in range(int(kwargs["len"]))]
        context["data"] = {
            "info1": "290",
            "info2": "076",
            "info3": "062",
        }
        return context
    

class Index(DBRead):
    template_name = "app_general/index.html"

    def get_context_data(self, request,  *args, **kwargs):
        return {}


class StudentRegistrationPage(DBRead):
    template_name = "app_general/student_registration_page.html"

    def get_context_data(self, request,  *args, **kwargs):
        context = {}

        context["date"] = {
            "days": [i for i in range(32)[1:]],
            "months": [i for i in range(13)[1:]],
            "years": [i for i in range(2022)[1990:][::-1]]
        }

        return context


class StudentRegistration(DBAction):

    def action(self, request, **kwargs):
        self.redirect_url = "app_general:login_page"

        post_data = dict(**request.POST)

        student_id = post_data["student_id"][0]
        name = post_data["name"][0]
        email = post_data["email"][0]
        phone_number = post_data["phone_number"][0]
        department = post_data["department"][0]
        password = post_data["password"][0]
        dob = {
            "day": post_data["day"][0],
            "month": post_data["month"][0],
            "year": post_data["year"][0],
        }
        retype_password = post_data["retype_password"][0]

        self.database.insert("students", [
            {
                "student_id": student_id,
                "name": name,
                "uiu_email": email,
                "phone_number": phone_number,
                "department": department,
                "password_hash": hashlib.sha256(password.encode("ASCII")).hexdigest(),
                "photo": "null",
                "dob": f"{dob['year']}-{dob['month']}-{dob['day']}"
            }
        ])

        # return super().action(request, **kwargs)


class LoginPage(DBRead):
    template_name = "app_general/login_page.html"

    def get_context_data(self, request,  *args, **kwargs):
        # return {}
        return {}


class Login(DBAction):
    
    def action(self, request, **kwargs):

        try:
            user = request.POST["user"]
            password = request.POST["password"]
        except Exception:
            self.redirect_url = "app_general:login_page"
            return

        user_domains = {
            "student": ["student_id", "uiu_email"],
            "teacher": ["employee_id", "uiu_email"]
        }

        user_data = None
        user_domain = None

        for key in user_domains.keys():
            
            user_data = self.database.get(f"{key}s", conditions={
                user_domains[key][0]: user,
                user_domains[key][1]: user,
            }, condition_connector = "or")
            
            if len(user_data) == 1:
                user_data = user_data[0]
                user_domain = key
                break

        if user_data is None or not self.verify_password(user_data, password):
            self.redirect_url = "app_general:login_page"
            return

        user_id = user_data[user_domains[user_domain][0]]

        request.session["user"] = {
            "login_status": True,
            "id": user_id,
            "domain": user_domain
        }

        request.session.set_expiry(24 * 3600)

        self.redirect_url = f"app_general:{user_domain}_dashboard_page"

    def verify_password(self, user, password):

        if len(user) == 0:
            return False

        given = hashlib.sha256(password.encode("ASCII")).hexdigest()
        # print(given)
        # print(user)
        return user["password_hash"] == given


class Logout(DBAction):
    
    def action(self, request, **kwargs):
        self.redirect_url = "app_general:login_page"
        del request.session["user"]


class TeacherDashboardPage(DBRead):

    template_name = "app_general/teacher_dashboard_page.html"

    def get_context_data(self, request,  *args, **kwargs):
        context = {}

        teacher_id = request.session["user"]["id"]
        sections = self.database.get('sections', conditions={
            "teacher_id": teacher_id
        })

        section_ids = [sections[i]['id'] for i in range(len(sections))]

        projects = []

        if len(section_ids) > 0:
            projects = self.database.get("projects", conditions={
                "section_id": section_ids,
                "status": 1
            })

        context['projects'] = []

        for project in projects:

            project["course"] = self.database.get("sections", ["name", "course_code", "course_name"], {"id": project["section_id"]})[0]
            project["team"] = [
                team_member["student_id"]
                for team_member in self.database.get("project_members", ["student_id"], conditions = {"project_id": project["id"]})
            ]

            context['projects'].append(project)

        teacher = self.database.get('teachers', conditions={"employee_id": teacher_id})[0]

        context["teacher"] = teacher

        return context


class ProjectProcessorTeacher(DBRead):
    template_name = "app_general/project_processor_teacher.html"

    def get_context_data(self, request,  *args, **kwargs):
        context = {}

        teacher_id = request.session["user"]["id"]
        project_status = kwargs["project_status"]

        sections = self.database.get('sections', conditions={
            "teacher_id": teacher_id
        })

        section_ids = [sections[i]['id'] for i in range(len(sections))]

        projects = []

        if len(section_ids) > 0:
            projects = self.database.get("projects", conditions={
                "section_id": section_ids,
                "status": project_status
            })

        context['projects'] = []

        for project in projects:

            project["course"] = self.database.get("sections", ["name", "course_code", "course_name"], {"id": project["section_id"]})[0]
            project["team"] = [
                team_member["student_id"]
                for team_member in self.database.get("project_members", ["student_id"], conditions = {"project_id": project["id"]})
            ]

            context['projects'].append(project)

        teacher = self.database.get('teachers', conditions={"employee_id": teacher_id})[0]

        context["teacher"] = teacher

        return context


class StudentDashboardPage(DBRead):
    template_name = "app_general/student_dashboard_page.html"

    def get_context_data(self, request,  *args, **kwargs):
        context = {}

        student_id = request.session["user"]["id"]

        project_ids = self.database.get("project_members", ["project_id"], conditions = {"student_id": student_id})
        context['projects'] = []

        for project_id in project_ids:
            project = self.database.get("projects", ["id", "title", "section_id"], conditions = {
                "id": project_id["project_id"],
                "status": 1
            })

            if len(project) == 0:
                continue

            project = project[0]

            project["course"] = self.database.get("sections", ["name", "course_code", "course_name"], {"id": project["section_id"]})[0]
            project["team"] = [
                team_member["student_id"]
                for team_member in self.database.get("project_members", ["student_id"], conditions = project_id)
            ]

            context['projects'].append(project)

        context["student"] = {
            "id": student_id,
            **self.database.get("students", ["name", "department"], {"student_id": student_id})[0],
        }

        return context


class ProjectProcessor(DBRead):
    template_name = "app_general/project_processor.html"

    def get_context_data(self, request,  *args, **kwargs):

        context = {}

        student_id = request.session["user"]["id"]
        project_status = kwargs["project_status"]

        project_ids = self.database.get("project_members", ["project_id"], conditions = {"student_id": student_id})
        context['projects'] = []

        for project_id in project_ids:
            project = self.database.get("projects", ["id", "title", "section_id"], conditions = {
                "id": project_id["project_id"],
                "status": project_status
            })

            if len(project) == 0:
                continue
            
            project = project[0]

            project["course"] = self.database.get("sections", ["name", "course_code", "course_name"], {"id": project["section_id"]})[0]
            project["team"] = [
                team_member["student_id"]
                for team_member in self.database.get("project_members", ["student_id"], conditions = project_id)
            ]

            project["status"] = project_status

            context['projects'].append(project)

        context["student"] = {
            "id": student_id,
            **self.database.get("students", ["name", "department"], {"student_id": student_id})[0],
        }

        return context
    

class ProjectDetailsPage(DBRead):
    database = MySql.db()

    template_name = "app_general/project_details_page.html"

    def get_context_data(self, request,  *args, **kwargs):

templates/app_general/booth_setup_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/app_general/booth_setup_page.css' %}">
        <title>Booth setup</title>
    </head>
    <body>
        
        {% include "../common/navbar.html" %}

        <h1 class="title">Setup Booth</h1><br>

        <div class="project_title">
            <h2>Project title: <span>{{ booth_details.title|upper }}</span></h2>
        </div>

        <div class="description">
            <h2>Project Descrition:</h2>
            <span> Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias asperiores sequi libero et inventore, veniam laboriosam eos incidunt modi nostrum totam commodi in vel aliquam. {{ booth_details.short_description }}</span>
        </div>

        <form action="{% url 'app_general:booth_setup' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" value="{{ booth_details.id }}" name="proj_id">

            <div>
                <label>Intro video</label>
                <input id="intro_video" name="intro_video" type="file" accept=".mp4,.mkv" required>
            </div>

            <div>
                <label>Report</label>
                <input id="report" name="report" type="file" accept=".pdf" required>
            </div>

            <div>
                <label>Video demo</label>
                <input id="demo_videos" name="demo_videos" type="file" accept=".mp4,.mkv" multiple>
            </div>

            <button type="submit">Setup</button>
        </form>

        <script src="{% static 'js/common/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/app_general/booth_setup_page' %}"></script>
    </body>
</html>

templates/app_general/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/app_general/index.css' %}">
        <title>Document</title>
    </head>
    <body>
        
        {% include "../common/navbar.html" %}
        
        <div class="registration_links">
            <a href="{% url 'app_general:student_registration_page' %}">
                <i class="fad fa-user-graduate"></i>
                <span>Join as student</span>
            </a>
        
            <a href="{% url 'app_general:student_registration_page' %}">
                <i class="fad fa-university"></i>
                <span>Join as teacher</span>
            </a>
        </div>

        <div class="login_link">
            <a href="{% url 'app_general:login_page' %}">
                <i class="fad fa-sign-in"></i>
                <span>Login</span>
            </a>
        </div>

        <script src="{% static 'js/common/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/app_general/index.js' %}"></script>
    </body>
</html>

templates/app_general/login_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/app_general/login_page.css' %}">
        <title>Document</title>
    </head>
    <body>
        
        {% include "../common/navbar.html" %}
        
        {% comment %} <h1 class="title">Login Page</h1>

        <div class="dashboard">
            <a href="{% url 'app_general:teacher_dashboard_page' %}">Teacher Dashboard</a>
            <a href="{% url 'app_general:student_dashboard_page' %}">Student Dashboard</a>
        </div> {% endcomment %}

        <form action="{% url 'app_general:login' %}" method="POST">
            {% csrf_token %}

            <div class="title">Login</div>

            <div class="user">
                <label for="user">E-mail or User ID:</label>
                <input id="user" type="text" name="user" placeholder="Enter you user ID or e-mail" required>
            </div>

            <div class="password">
                <label for="password">Password:</label>
                <input id="password" type="password" name="password" placeholder="Enter password" required>
            </div>

            <input type="submit" name="login" value="Login">
        </form>

        <script src="{% static 'js/common/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/app_general/login_page.js' %}"></script>
    </body>
</html>

templates/app_general/project_details_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
		{% comment %} <style>
			a:link, a:visited {
			background-color: #33ff5d;
			color: white;
			padding: 14px 25px;
			text-align: center;
			text-decoration: none;
			display: inline-block;
			}

			a:hover, a:active {
			background-color: green;
			}
			</style> 
		{% endcomment %}
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/app_general/project_details_page.css' %}">
        <title>Project Details Page</title>
    </head>
    <body>
        
        {% include "../common/navbar.html" %}

        <h1 class="title">Project title: {{title}} </h1>

        <div class="details">
			<div class="course_name">
				<h2>Course: <span>{{ course }}</span></h2>
			</div>
				
			<div class="short_description">
				<h2>Short Description:<h2>
				<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorum ea incidunt ratione? Voluptatum quas aliquid debitis, possimus magnam reprehenderit deleniti neque rerum dolorem! Necessitatibus, voluptas. {{ description }} </p>
			</div>

			<div class="project_member_details">
				<h2>Project Members:</h2>
				<table border cellspacing="0" cellpadding="0">
				<tr>
					<th>Student Name</th>
					<th>Student ID</th>
				</tr>

				{% for member in members %}
					<tr>
					<td>{{member.name}}</td>
					<td>{{member.id}}</td>
					</tr>
				{% endfor %}
				</table>
			</div>
        </div>
		
		{% if status == 0 %}
        	<a class="approve" href="{% url 'app_general:project_approve' id%}">Approve</a>
		{% endif %}

        <script src="{% static 'js/common/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/app_general/project_details_page.js' %}"></script>
    </body>
</html>

templates/app_general/project_processor.html
{% load general_extras %}

{% for project in projects %}
    <div class="project">
        <div class="project-header">
            <span class="project-name">{{ project.title|abstractify:17 }}</span>
            <span class="course-name">{{ project.course.course_name }}</span>
            <span class="course-code-section">Course Code: {{ project.course.course_code }} | Section: {{ project.course.name }}</span>
        </div>
        <div class="project-team">
            <span>Team: </span>
            <div class="team-members">
                {% for team_member in project.team %}
                    <span class="team-member">{{ team_member }}</span>
                {% endfor %}
            </div>
        </div>
        <a href="{% url 'app_general:booth_setup_page' project.id %}">
            <i class="fad fa-cog"></i>
        </a>
    </div>
{% endfor %}

templates/app_general/project_processor_teacher.html
{% load general_extras %}

{% for project in projects %}
    <div class="project">
        <div class="project-header">
            <span class="project-name">{{ project.title|abstractify:17 }}</span>
            <span class="course-name">{{ project.course.course_name }}</span>
            <span class="course-code-section">Course Code: {{ project.course.course_code }} | Section: {{ project.course.name }}</span>
        </div>
        <div class="project-team">
            <span>Team: </span>
            <div class="team-members">
                {% for team_member in project.team %}
                    <span class="team-member">{{ team_member }}</span>
                {% endfor %}
            </div>
        </div>
        <a href="{% url 'app_general:project_details_page' project.id %}">
            {% comment %} <i class="fad fa-cog"></i> {% endcomment %}
            <i class="fad fa-external-link"></i>
        </a>
    </div>
{% endfor %}

templates/app_general/student_dashboard_page.html
<!DOCTYPE html>
{% load static %}
{% load general_extras %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/app_general/student_dashboard_page.css' %}">
        <title>{{ session.user.domain }} Dashboard</title>
    </head>
    <body>
        
        {% include "../common/navbar.html" %}

		<div class="dashboard-container">
			<div class="header">
				<div class="user-info">
					<div class="user-name">{{ student.name|abstractify:20 }}</div>
					<div class="vr"></div>
					<div class="user-designation">
						<span class="varsity">United International University</span>
						<span class="id-dept">{{ student.id }}, Department of {{ student.department }}</span>
					</div>
				</div>
				<div class="dashboard-controls">
					<a href="{% url 'app_club_ff:fest_registration_page' %}">Fest Registration</a>
					<a href="{% url 'app_cse_ps:project_registration_page' %}">Project Registration</a>
					{% comment %} <a href="#">Edit Profile</a> {% endcomment %}
				</div>				
			</div>
			<div class="projects-management">
				<div class="tab-buttons">
					<button class="active" id="appr_proj">Approved Projects</button>
					<div class="button-devider"></div>
					<button id="appr_pen_proj">Approval Pending Projects</button>
				</div>
				<div class="projects">
					{% for project in projects %}
						<div class="project">
							<div class="project-header">
								<span class="project-name">{{ project.title|abstractify:17 }}</span>
								<span class="course-name">{{ project.course.course_name }}</span>
								<span class="course-code-section">Course Code: {{ project.course.course_code }} | Section: {{ project.course.name }}</span>
							</div>
							<div class="project-team">
								<span>Team: </span>
								<div class="team-members">
									{% for team_member in project.team %}
										<span class="team-member">{{ team_member }}</span>
									{% endfor %}
								</div>
							</div>
							<a href="{% url 'app_general:booth_setup_page' project.id %}">
								<i class="fad fa-cog"></i>
							</a>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>

        <script src="{% static 'js/common/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/app_general/student_dashboard_page.js' %}"></script>
    </body>
</html>

templates/app_general/student_registration_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/app_general/student_registration_page.css' %}">
        <title>Document</title>
    </head>
    <body>
        
        {% include "../common/navbar.html" %}
        
        <h1 class="title">Registration</h1>
        
        <form action="{% url 'app_general:student_registration' %}" method="POST" enctype="multipart/form-data">
        
            {% csrf_token %}

            <div class="student_id">
                <label for="student_id">Student ID:</label>
                <input type="text" name="student_id" id="student_id">
            </div>
            <div class="name">
                <label for="name">Name: </label>
                <input type="text" name="name" id="name">
            </div>
            <div class="email">
                <label for="email">Email: </label>
                <input type="text" name="email" id="email">
            </div>

            <div class="phone_number">
                <label for="phone_number">Phone Number: </label>
                <input type="text" name="phone_number" id="phone_number">
            </div>

            <div>
                <label for="department">Department:</label>
                <select name="department" id="department">
                    <option value="cse">CSE</option>
                    <option value="eee">EEE</option>
                    <option value="civil">Civil</option>
                </select>
            </div>

            <div class="dob">
                <label>Date of Birth: </label>
                <span>
                    <select name="day" id="day">
                        {% for day in date.days %}
                            <option value="{{ day }}">{{ day }}</option>
                        {% endfor %}
                    </select>
                    <select name="month" id="month">
                        {% for month in date.months %}
                            <option value="{{ month }}">{{ month }}</option>
                        {% endfor %}
                    </select>
                    <select name="year" id="year">
                        {% for year in date.years %}
                            <option value="{{ year }}">{{ year }}</option>
                        {% endfor %}
                    </select>
                </span>
            </div>

            <div class="password">
                <label for="password">Passoword:</label>
                <input type="password" id="password" name="password">
            </div>
            
            <div class="retype_password">
                <label for="retype_password">Retype Passoword:</label>
                <input type="password" id="retype_password" name="retype_password">
            </div>

            <input type="submit" name="submit" value="Submit">

        </form>

        <script src="{% static 'js/common/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/app_general/student_registration.js' %}"></script>
    </body>
</html>

templates/app_general/test.html
{% for l in len %}
    <div>
        <span>Info_{{ l }}: {{ data.info1 }}</span>
        <span>Info_{{ l }}: {{ data.info2 }}</span>
        <span>Info_{{ l }}: {{ data.info3 }}</span>
    </div>
{% endfor %}