app_admin/urls.py
from django.conf import settings
from django.urls import path, include
from . import views
from app_cse_ps import urls as app_cse_ps_urls
from app_club_ff import urls as app_club_ff_urls

LOGIN_REQUIRED = True

app_name = "app_admin"

urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("prize_giving_page/", views.PrizeGivingPage.as_view(), name="prize_giving_page"),
    path("give_award/", views.give_award, name="give_award"),
    path("get_projects_by_course_code/<course_code>/", views.get_projects_by_course_code, name="get_projects_by_course_code"),
    path("get_courses_by_trimester/<trimester>/",views.get_course_by_trimester,name="get_course_by_trimester"),

]

app_club_ff/urls.py
from django.conf import settings
from django.urls import path
from . import views

from django.shortcuts import render
from my_modules.base_views import DBAction, DBRead
from django.views.generic import TemplateView
from my_modules.database import MySql
from django.http import HttpResponse
import json

app_name = "app_club_ff"

urlpatterns = [
    path("index/", views.Index.as_view(), name="index"),
    path("fest_registration_page/",views.FestRegistrationPage.as_view(login_required=True), name="fest_registration_page"),
    path("fest_registration/", views.FestRegistration.as_view(login_required=True), name="fest_registration"),
    path("get_club_names/", views.get_club_names, name="get_club_names"),
    path("get_cff_years/", views.get_cff_years, name="get_cff_years"),
    path("get_filtered_cff/<club_name>/<year>", views.get_filtered_cff, name="get_filtered_cff"),
    path("fest_feed_page/", views.FestFeed.as_view(), name="fest_feed_page"),
    path("post_processor/<club_id>/<criteria>/<offset>/", views.PostProcessor.as_view(), name="post_processor"),
    path("archive_cff_booths_page/", views.ArchiveCffBooths.as_view(), name="archive_cff_booths_page"),
]

app_cse_ps/urls.py
from django.conf import settings
from django.urls import path
from . import views

LOGIN_REQUIRED = True

app_name = "app_cse_ps"

urlpatterns = [
    path("index/", views.Index.as_view(), name="index"),
    path("project_registration_page/",views.ProjectRegistrationPage.as_view(login_required=True), name="project_registration_page"),
    path("project_registration/",views.ProjectRegistration.as_view(login_required=True), name="project_registration"),
    path("course_list_page/", views.CourseListPage.as_view(), name="course_list_page"),
    path("booth_list_page/<course_code>", views.BoothListPage.as_view(), name="booth_list_page"),
    path("get_course_names/", views.get_course_names, name="get_course_names"),
    path("get_sections/<course_code>", views.get_sections, name="get_sections"),
    path("get_student/<student_id>", views.get_student, name="get_student"),
    path("archieve_projects/", views.ArchiveProjects.as_view(), name="archieve_projects"),
    path("get_trimesters/", views.get_trimesters, name="get_trimesters"),
    path("get_filtered_archeive_projects/<course_code>/<trimester>", views.get_filtered_archeive_projects, name="get_filtered_archeive_projects"),
    path("project_booth_page/<project_id>/", views.ProjectBoothPage.as_view(), name="project_booth_page"),    
    path("comment_loader/<project_id>/<already_loaded>/", views.CommentLoader.as_view(), name="comment_loader"),
    path("commenter/", views.Commenter.as_view(login_required=True), name="commenter"),
]

app_general/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "app_general"

urlpatterns = [
    path("index/", views.Index.as_view(), name="index"),
    path("student_registration_page/", views.StudentRegistrationPage.as_view(logout_required=True), name="student_registration_page"),
    path("student_registration/", views.StudentRegistration.as_view(), name="student_registration"),
    path("login_page/", views.LoginPage.as_view(logout_required=True), name="login_page"),
    path("login/", views.Login.as_view(logout_required=True), name="login"),
    path("logout/", views.Logout.as_view(login_required=True), name="logout"),
    path("teacher_dashboard_page/", views.TeacherDashboardPage.as_view(login_required=True), name="teacher_dashboard_page"),
    path("student_dashboard_page/", views.StudentDashboardPage.as_view(login_required=True), name="student_dashboard_page"),
    path("project_processor_teacher/<project_status>/", views.ProjectProcessorTeacher.as_view(login_required=True), name="project_processor_teacher"),
    path("project_processor/<project_status>/", views.ProjectProcessor.as_view(login_required=True), name="project_processor"),
    path("project_details_page/<project_id>/", views.ProjectDetailsPage.as_view(), name="project_details_page"),
    path("project_approve/<project_id>/", views.ProjectApprove.as_view(), name="project_approve"),
    path("booth_setup_page/<project_id>/",views.BoothSetupPage.as_view(), name="booth_setup_page"),
    path("booth_setup/",views.BoothSetup.as_view(), name="booth_setup"),
    # path("test_page/", views.TestPage.as_view(), name="test_page"),
    path("test_page/", views.TestPage.as_view(), name="test_page"),
    path("test/<len>/", views.Test.as_view(), name="test"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uiu_emas/urls.py
from django.contrib import admin
from django.urls import path, include
from app_cse_ps import urls as app_cse_ps_urls
from app_club_ff import urls as app_club_ff_urls
from app_admin import urls as app_admin_urls
from app_general import urls as app_general_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(app_admin_urls)),
    path('admin_django/', admin.site.urls),
    path('cse_ps/', include(app_cse_ps_urls), name="cse_ps"),
    path('club_ff/', include(app_club_ff_urls), name="club_ff"),
    path('general/', include(app_general_urls), name="general"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_admin/views.py
from django.shortcuts import render
from my_modules.base_views import DBAction,DBRead
from django.views.generic import TemplateView
from my_modules.database import MySql
from django.http import HttpResponse
import json

# Create your views here.

class Index(DBRead):
    template_name = "app_admin/index.html"

    def get_context_data(self, request,  *args, **kwargs):
        return {}

# class BoothSetupPage(DBRead):
#     template_name = 'app_general/booth_setup_page.html'
#     database = MySql.db()
#
#     def get_context_data(self, request,  *args, **kwargs):
#         self.boothid = kwargs['project_id']
#         # self.boothid = 1  # delete this line
#         context = {}
#         booth_details = self.database.query(f'SELECT id,title,short_description FROM projects WHERE id={self.boothid}')
#         context['booth_details'] = {'id': booth_details[0][0], 'title': booth_details[0][1],
#                                     'short_description': booth_details[0][2]}
#         return context

class PrizeGivingPage(DBRead):
    template_name = "app_admin/prize_giving_page.html"

    def get_context_data(self, *args ,**kwargs):
        context = {}
        trimesters = self.database.query(f'SELECT DISTINCT trimester FROM sections')
        context['trimesters'] = list(trimesters[0])
        #print(context)
        return context

def get_course_by_trimester(request,**kwargs):

    #print(kwargs)
    database = MySql.db()
    context = {}
    courses = database.query(f'SELECT DISTINCT course_code,course_name FROM sections WHERE trimester={kwargs["trimester"]}')
    if len(courses) > 0:
        context["message"] = "OK"
    else:
        context["message"] = "NOT FOUND"

    context["data"] = []
    list = ['course_code', 'course_name']
    for tup in courses:
        context["data"].append({list[0]: tup[0], list[1]: tup[1]})
    context = json.dumps(context)
    return HttpResponse(context)

def get_projects_by_course_code(request,**kwargs):
    #print("efwfwgwrgwrgrwgwrgwrrgwrgwgrwgwrgwrg")
    #print(kwargs)
    database = MySql.db()
    context = {}
    section_ids = database.query(f'SELECT id FROM sections WHERE course_code="{kwargs["course_code"]}"')
    section_ids =[ s[0] for s in section_ids]
    ids = ""
    for temp in section_ids:
        ids += str(temp) + ","
    ids = ids[:-1]
    prized_proj_ids=database.query(f'SELECT project_id FROM prizes')
    prized_proj_ids = [p[0] for p in prized_proj_ids]
    pids = ""
    for temp in prized_proj_ids:
        pids += str(temp) + ","
    pids = pids[:-1]
    if len(prized_proj_ids)==0:
        project_ids = database.query(f'SELECT id,title FROM projects WHERE section_id IN ({ids})')
    else:
        project_ids = database.query(f'SELECT id,title FROM projects WHERE section_id IN ({ids}) AND id NOT IN ({pids})')

    if len(project_ids) > 0:
        context["message"] = "OK"
    else:
        context["message"] = "NOT FOUND"

    context["data"] = []
    list = ['project_id','title']
    for tup in project_ids:
        context["data"].append({list[0]: tup[0], list[1]: tup[1]})
    context = json.dumps(context)
    return HttpResponse(context)


def give_award(request, **kwargs):
    context = {}

    trimester = request.POST["trimester"]
    project_id = request.POST["project"]
    course_code = request.POST["course_code"]
    prize = request.POST["prize"]
    database=MySql.db()

    #cheking if the prize is already given - if given, error message will be shown in page
    all_prized_proj_ids = database.query(f'SELECT project_id FROM prizes')
    all_prized_proj_ids = [p[0] for p in all_prized_proj_ids]
    #print(f'{all_prized_proj_ids} {project_id}')
    for i in all_prized_proj_ids:
        #print(f'{type(i)} : {i},{type(project_id)} : {project_id}, {project_id==i}')

        if int(project_id)==i:
            context["message"] = "Team already won a prize"
            context = json.dumps(context)
            return HttpResponse(context)

    section_ids = database.query(f'SELECT id FROM sections WHERE course_code="{course_code}" AND trimester = {trimester}')
    section_ids = [s[0] for s in section_ids]

    prized_proj_ids = database.query(f'SELECT project_id FROM prizes WHERE prize = {prize}')
    prized_proj_ids = [p[0] for p in prized_proj_ids]
    pids = ""
    for temp in prized_proj_ids:
        pids += str(temp) + ","
    pids = pids[:-1] #project id of prize wining projects

    if len(prized_proj_ids)!=0:
        prized_section_ids = database.query(f'SELECT section_id FROM projects WHERE id IN ({pids})')
        prized_section_ids = [p[0] for p in prized_section_ids]

        for x in prized_section_ids:
            for y in section_ids:
                if x==y:
                    context["message"] = "Prize already given"
                    context = json.dumps(context)
                    return HttpResponse(context)


    #insering to database
    context["message"] = "Prize successfully added"
    student_ids = database.query(f'SELECT student_id FROM project_members WHERE project_id = {project_id}')
    student_ids = [s[0] for s in student_ids]
    for id in student_ids:
        database.query(f'INSERT INTO prizes (project_id,student_id,prize) VALUES ("{project_id}","{id}","{prize}")')
    context = json.dumps(context)
    return HttpResponse(context)

templates/app_admin/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/app_admin/index.css' %}">
        <title>Document</title>
    </head>
    <body>
        
        {% include "../common/navbar.html" %}

        <h1 class="name">UIU&nbsp&nbsp&nbspEMAS</h1>
        <div class="all_app">
            {% comment %} <div class="app_admin">
                <a href="">
                    <i class="fad fa-user-lock"></i>
                    <span class="heading">Admin</span>
                </a>
            </div> {% endcomment %}
            <div class="app_cse_ps">
                <!-- <a href="cse_ps/"> -->
                <a href="{% url 'app_cse_ps:index' %}">
                    <i class="fad fa-drafting-compass"></i>
                    <span class="heading">CSE Project Show</span>
                </a>
            </div>
            <div class="app_club_ff">
                <a href="{% url 'app_club_ff:index' %}">
                    <i class="fad fa-person-sign"></i>
                    <span class="heading">Club Forum Fest</span>
                </a>
            </div>
            {% comment %} <div class="app_general">
                <a href="{% url 'app_general:index' %}">
                    <i class="fad fa-share-alt"></i>
                    <span class="heading">General</span>
                </a>
            </div> {% endcomment %}
        </div>
        
        <script src="{% static 'js/common/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/app_admin/index.js' %}"></script>
    </body>
</html>

templates/app_admin/prize_giving_page.html
<!DOCTYPE html>
{%  load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/app_admin/prize_giving_page.css' %}">
        <title>Give Prizes</title>
    </head>
    <body>
        {% include "../common/navbar.html" %}
        <h1 class="title">Give prize</h1>

        <form>
            {% csrf_token %}
            <div>
                <label>Trimester::</label>
                <select id="trimester" name="trimester" required>
                    <option value="0">Select</option>
                    {% for trimester in trimesters %}
                        <option value="{{ trimester }}">{{ trimester }}</option>
                    {% endfor %}
                </select>
            </div>

            <div>
                <label>Course:</label>
                <select id="courses" name="courses" required>
                </select>
            </div>

            <div>
                <label>Team Name:</label>
                <select id="projects" name="projects" required>
                </select>
            </div>

            <div>
                <label>Prize:</label>
                <div class="prizes">
                    <div class="prize" id="silver">
                        <label for="s_prize"><i class="fad fa-medal prize-silver"></i></label>
                        <input type="radio" id="s_prize" name="prize" value="2">
                    </div>
                    <div class="prize" id="gold">
                        <label for="f_prize"><i class="fad fa-medal prize-gold"></i></label>
                        <input type="radio" id="f_prize" name="prize" value="1">
                    </div>
                    <div class="prize" id="bronze">
                        <label for="t_prize"><i class="fad fa-medal prize-bronze"></i></label>
                        <input type="radio" id="t_prize" name="prize"  value="3">
                    </div>
                </div>
            </div>
            <input type="button" id="submit" value="Give Award">
        </form>

        <div id="error"></div>

    </body>
    <script src="{% static 'js/common/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/app_admin/prize_giving_page.js' %}"></script>
</html>