app_cse_ps/urls.py
from django.conf import settings
from django.urls import path
from . import views

LOGIN_REQUIRED = True

app_name = "app_cse_ps"

urlpatterns = [
    path("index/", views.Index.as_view(), name="index"),
    path("project_registration_page/",views.ProjectRegistrationPage.as_view(login_required=True), name="project_registration_page"),
    path("project_registration/",views.ProjectRegistration.as_view(login_required=True), name="project_registration"),
    path("course_list_page/", views.CourseListPage.as_view(), name="course_list_page"),
    path("booth_list_page/<course_code>", views.BoothListPage.as_view(), name="booth_list_page"),
    path("get_course_names/", views.get_course_names, name="get_course_names"),
    path("get_sections/<course_code>", views.get_sections, name="get_sections"),
    path("get_student/<student_id>", views.get_student, name="get_student"),
    path("archieve_projects/", views.ArchiveProjects.as_view(), name="archieve_projects"),
    path("get_trimesters/", views.get_trimesters, name="get_trimesters"),
    path("get_filtered_archeive_projects/<course_code>/<trimester>", views.get_filtered_archeive_projects, name="get_filtered_archeive_projects"),
    path("project_booth_page/<project_id>/", views.ProjectBoothPage.as_view(), name="project_booth_page"),    
    path("comment_loader/<project_id>/<already_loaded>/", views.CommentLoader.as_view(), name="comment_loader"),
    path("commenter/", views.Commenter.as_view(login_required=True), name="commenter"),
]

uiu_emas/urls.py
from django.contrib import admin
from django.urls import path, include
from app_cse_ps import urls as app_cse_ps_urls
from app_club_ff import urls as app_club_ff_urls
from app_admin import urls as app_admin_urls
from app_general import urls as app_general_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(app_admin_urls)),
    path('admin_django/', admin.site.urls),
    path('cse_ps/', include(app_cse_ps_urls), name="cse_ps"),
    path('club_ff/', include(app_club_ff_urls), name="club_ff"),
    path('general/', include(app_general_urls), name="general"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_cse_ps/views.py
from django.shortcuts import render
from my_modules.base_views import DBAction, DBRead
from django.views.generic import TemplateView
from my_modules.database import MySql
from django.http import HttpResponse
import json

# Create your views here.

class Index(DBRead):
    template_name = "app_cse_ps/index.html"


class ProjectRegistrationPage(DBRead):
    template_name = "app_cse_ps/project_registration_page.html"
    database = MySql.db()

    def get_context_data(self, request,  *args, **kwargs):
        context = {}

        unique_sections_tuple = self.database.query("SELECT DISTINCT id, course_code, course_name, name FROM sections")
        context["data"] = []
        list = ['id', 'course_code','course_name','name']
        for tup in unique_sections_tuple:
            context["data"].append({list[0]:tup[0],list[1]:tup[1],list[2]:tup[2],list[3]:tup[3]})
        return context


class ArchiveProjects(DBRead):
    template_name = "app_cse_ps/archieve_projects_page.html"

    def get_context_data(self, request,  *args, **kwargs):
        context = {}
        projects = self.database.query("SELECT id, title, short_description, section_id FROM projects WHERE `status` = 1")
        context["data"] = []
        list = ['id', 'title', 'short_description', 'project_members', 'course_name', 'trimester']

        for tup in projects:
            members_id_tup = self.database.query(f"SELECT student_id FROM project_members WHERE project_id = {tup[0]}")
            members_id = []
            for member in members_id_tup:
                members_id.append(member[0])
            members_name = []
            for member in members_id:
                members_name.append(self.database.query(f"SELECT name FROM students WHERE student_id = {member}")[0][0])

            members_info = []
            for i in range(len(members_name)):
                members_info.append({'id' : members_id[i], 'name' : members_name[i]})

            course_trimester = self.database.query(f"SELECT course_name, trimester FROM sections WHERE sections.id = {tup[3]}")
            context["data"].append({list[0]:tup[0],list[1]:tup[1],list[2]:tup[2], list[3]: members_info, list[4]: course_trimester[0][0], list[5]: course_trimester[0][1]})
        return context


class ProjectRegistration(DBAction):
    def action(self, request, **kwargs):
        self.redirect_url = "app_cse_ps:index"
        post_data = dict(**request.POST)

        project_title = post_data["project_title"][0]
        section_id =  post_data["section"][0]
        short_description = post_data["short_description"][0]
        project_members = post_data["project_members"][0]

        project_members = project_members.strip().split(',')

        try:
            self.database.query(f'INSERT INTO projects(title, section_id, short_description, trimester) VALUES ("{project_title}", "{section_id}", "{short_description}", "213")')
        except:
            self.redirect_url = "app_cse_ps:project_registration_page"
            return

        project_id = self.database.query(f'SELECT id from projects where title = "{project_title}" and short_description = "{short_description}"')[0][0]
        for member in project_members:
            self.database.query(f'INSERT into project_members(project_id, student_id) VALUE ("{project_id}", "{member.strip()}")')
        return


class CourseListPage(DBRead):

    template_name = "app_cse_ps/course_list_page.html"

    def get_context_data(self, request, *args, **kwargs):
        context = {}
        context["courses"] = [
            # {
            #     "name": "Object Oriented Programming Laboratory",
            #     "code": "CSI TST",
            #     "num_sections": 4,
            #     "num_projects": 13
            # }
        ]

        courses = self.database.get_distinct("sections", ["course_code", "course_name"])

        for course in courses:
            num_sections = self.database.count("sections", {
                "course_code": course["course_code"],
            })

            section_ids = self.database.get("sections", ["id"], conditions = {
                "course_code": course["course_code"]
            })

            num_projects = self.database.count("projects", {
                "section_id": [section_id["id"] for section_id in section_ids]
            }, other_clauses=["and status=1"])

            context["courses"].append({
                "name": course["course_name"],
                "code": course["course_code"],
                "num_sections": num_sections,
                "num_projects": num_projects,
            })

        print(context)

        return context


class BoothListPage(DBRead):

    template_name = "app_cse_ps/booth_list_page.html"

    def get_context_data(self, request, *args, **kwargs):
        context = {}
        course_code = kwargs["course_code"]

        section_ids = self.database.get("sections", ["id"], {
            "course_code": course_code
        })

        projects = self.database.get("projects", ["id", "title", "short_description"], conditions={
            "section_id": [section_id["id"] for section_id in section_ids]
        }, other_clauses = ["and status=1"])

        for i in range(len(projects)):
            projects[i]["members"] = self.database.get("project_members", ["student_id"], {
                "project_id": projects[i]["id"]
            })

            for j in range(len(projects[i]["members"])):
                projects[i]["members"][j] = dict(**projects[i]["members"][j], **self.database.get("students", ["name"], {
                    "student_id": projects[i]["members"][j]["student_id"]
                })[0])

        context["projects"] = projects

        return context


def get_course_names(request):
    database = MySql.db()
    course_list = database.query("SELECT DISTINCT course_code, course_name FROM sections")
    context = {}
    context["data"] = []
    list = ['course_code','course_name']
    for tup in course_list:
        context["data"].append({list[0]:tup[0],list[1]:tup[1]})
    context = json.dumps(context)
    return HttpResponse(context)


def get_sections(request, course_code):
    database = MySql.db()
    section_list = database.query(f"SELECT id, name FROM sections WHERE course_code = '{course_code}'")
    context = {}
    context["data"] = []
    list = ['id','name']
    for tup in section_list:
        context["data"].append({list[0]:tup[0],list[1]:tup[1]})
    context = json.dumps(context)
    return HttpResponse(context)


def get_student(request, student_id):
    database = MySql.db()
    student_info = database.query(f"SELECT name, department FROM students WHERE student_id = '{student_id}'")
    context = {}
    if len(student_info) > 0:
        context["message"] = "OK"
    else:
        context["message"] = "NOT FOUND"

    context["data"] = []
    list = ['name', 'department']
    for tup in student_info:
        context["data"].append({list[0]:tup[0],list[1]:tup[1]})
    context = json.dumps(context)
    return HttpResponse(context)


def get_trimesters(request):
    database = MySql.db()
    trimesters = database.query("SELECT DISTINCT trimester FROM projects ORDER BY trimester ASC")
    context = {}
    context["data"] = []
    list = ['trimester']
    for tup in trimesters:
        context["data"].append({list[0]:tup[0]})
    context = json.dumps(context)
    print(context)
    return HttpResponse(context)


def get_filtered_archeive_projects(request, course_code, trimester):
    database = MySql.db()
    print(course_code)
    print(trimester)
    if course_code!='NULL' and trimester!='NULL':
        projects = database.query(f"SELECT projects.id, projects.title, projects.short_description, sections.course_name, projects.trimester FROM projects JOIN sections ON projects.section_id = sections.id WHERE projects.status = 1 and projects.trimester = '{trimester}' and sections.course_code = '{course_code}'")
    elif course_code!='NULL':
        projects = database.query(f"SELECT projects.id, projects.title, projects.short_description, sections.course_name, projects.trimester FROM projects JOIN sections ON projects.section_id = sections.id WHERE projects.status = 1 and sections.course_code = '{course_code}'")
    elif trimester!='NULL':
        projects = database.query(f"SELECT projects.id, projects.title, projects.short_description, sections.course_name, projects.trimester FROM projects JOIN sections ON projects.section_id = sections.id WHERE projects.status = 1 and projects.trimester = '{trimester}'")
    else:
        projects = database.query(f"SELECT projects.id, projects.title, projects.short_description, sections.course_name, projects.trimester FROM projects JOIN sections ON projects.section_id = sections.id WHERE projects.status = 1")

    context = {}
    context["data"] = []
    list = ['id', 'title', 'short_description', 'project_members', 'course_name', 'trimester']

    for tup in projects:
        members_id_tup = database.query(f"SELECT student_id FROM project_members WHERE project_id = {tup[0]}")
        members_id = []
        for member in members_id_tup:
            members_id.append(member[0])
        members_name = []
        for member in members_id:
            members_name.append(database.query(f"SELECT name FROM students WHERE student_id = {member}")[0][0])

        members_info = []
        for i in range(len(members_name)):
            members_info.append({'id' : members_id[i], 'name' : members_name[i]})

        context["data"].append({list[0]:tup[0],list[1]:tup[1],list[2]:tup[2], list[3]: members_info, list[4]: tup[3], list[5]: tup[4]})
    context = json.dumps(context)
    print(context)
    return HttpResponse(context)


class ProjectBoothPage(DBRead):

    template_name = "app_cse_ps/project_booth_page.html"

    def get_context_data(self, request, *args, **kwargs):
        context = {}

        project_id = kwargs["project_id"]

templates/app_cse_ps/archieve_projects_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/app_cse_ps/archieve_projects_page.css' %}">
        <title>Document</title>
    </head>
    <body>

        {% include "../common/navbar.html" %}

        <h1 class="title">Archived UIU CSE Project Show</h1>

        {% comment %} <h3 class="instructions"><i class="fad fa-asterisk"></i>Select a booth to view its content</h3> {% endcomment %}

        <div class="filter">
            <select name="course_filter" id="course_filter">
                <option value=""> Course </option>
            </select>

            <select name="trimester_filter" id="trimester_filter">
                <option value=""> Trimester </option>
            </select>

            <button type="button" name="filter" id="filter">Apply Filter</button>
        </div>

        <div class="booth_thumbnails" id = "booth_thumbnails">
            {% for project in data %}
                <div class="booth_thumbnail" course_name = "{{ project.course_name }}" trimester = "{{ project.trimester }}" >
                    <div class="project_name">
                        <span>Project name:</span><span>{{ project.title }}</span>
                    </div>
                    <div class="description">
                        <span>Description:</span><span>{{ project.short_description }}</span>
                    </div>

                    <div class="project_members">
                        <h2>Project Members:</h2>
                        <div class="members">
                            {% for member in project.project_members %}
                                <div>
                                    <span class="id">{{ member.id }} | </span>
                                    <span class="id">{{ member.name }}</span>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% comment %} use this id, if needed {{project.id}} {% endcomment %}
                </div>
            {% endfor %}
        </div>

        <script src="{% static 'js/common/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/app_cse_ps/archieve_projects_page.js' %}"></script>
    </body>
</html>

templates/app_cse_ps/booth_list_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/app_cse_ps/booth_list_page.css' %}">
        <title>Document</title>
    </head>
    <body>
        
        {% include "../common/navbar.html" %}
                
        <h1 class="title">UIU CSE Project Show</h1>
        
        <div class="instructions"><i class="fad fa-asterisk"></i>Select a booth to view its content</div>

        {% for project in projects %}
            <div class="booth_thumbnail">
                <div class="project_name">
                    <span>Project name:</span><span>{{ project.title }}</span>
                </div>
                <div class="description">
                    <span>Description:</span><span>{{ project.short_description }} Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium quas, reiciendis facilis possimus ratione, animi inventore vero numquam dolorum perferendis at quod magnam saepe? Numquam.</span>
                </div>

                <div class="project_members">
                    <h2>Project Members:</h2>
                    <div class="members">
                        {% for member in project.members %}
                            <div>
                                <span class="id">{{ member.student_id }} | </span>
                                <span class="id">{{ member.name }}</span>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <a class="visit_link" href="{% url 'app_cse_ps:project_booth_page' project.id %}">Visit Booth</a>
            </div>         
        {% endfor %}

        <script src="{% static 'js/common/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/app_cse_ps/booth_list_page.js' %}"></script>
    </body>
</html>

templates/app_cse_ps/comment_processor.html
{% for comment in comments %}
    <div>
        <span class="commenter">{{ comment.user_id }}</span>
        <span class="colon">:</span>
        <span class="comment">{{ comment.comment }}</span> 
    </div>
{% endfor %}

{% if length != 0 %}
    <span id="comment-length" length="{{ length }}"></span>
{% endif %}

templates/app_cse_ps/course_list_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/app_cse_ps/course_list_page.css' %}">
        <title>Document</title>
    </head>
    <body>
        
        {% include "../common/navbar.html" %}
        
        <h1 class="title">UIU CSE Project Show</h1>
        
        <h3 class="instructions"><i class="fad fa-asterisk"></i>Select a course to explore its projects</h3>

        <div class="courses">
            {% for course in courses %}
                <a href="{% url 'app_cse_ps:booth_list_page' course.code %}">
                    <span>{{ course.name }}</span>
                    <span>{{ course.code }} | Number of Sections: {{ course.num_sections }} | Number of Projects: {{ course.num_projects }}</span>
                </a>
            {% endfor %}
        </div>

        <script src="{% static 'js/common/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/app_cse_ps/course_list_page.js' %}"></script>
    </body>
</html>

templates/app_cse_ps/index.html
{% load static %}
<html>
    <head>
        <title>UIU CSE Project Show</title>
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/app_cse_ps/index.css' %}">
    </head>
    <body>

        {% include "../common/navbar.html" %}

        <h1 class="title">UIU CSE Project Show</h1>

        <div class="options">
            <a href="{% url 'app_cse_ps:course_list_page' %}">
                <i class="fad fa-users-class"></i>
                <span>Project Booths</span>
            </a>
            <a href="{% url 'app_cse_ps:archieve_projects' %}">
                <i class="fad fa-archive"></i>  
                <span>Archive</span>
            </a>
        </div>

        <script src="{% static 'js/common/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/app_general/project_registration_page.js' %}"></script>
    </body>
</html>

templates/app_cse_ps/project_booth_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/app_cse_ps/project_booth_page.css' %}">
        <title>Document</title>
    </head>
    <body>
        
        {% include "common/navbar.html" %}
        
        <h1 class="title">{{ project.title }}</h1>

        <div class="project">
            <div class="description">{{ project.short_description }}</div>
            <div class="file_section">
                <div>Contents:</div>
                <div class="files">
                    {% if project.intro_video != None %}
                        <a href="{{ MEDIA_URL }}{{ project.intro_video }}"><i class="fad fa-film"></i></a>
                    {% endif %}
                    {% if project.report != None %}
                        <a href="{{ MEDIA_URL }}{{ project.report }}"><i class="fad fa-file-chart-pie"></i></i></a>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="comment-box">
            <div class="comment-viewer" project_id="{{ project.id }}">
                {% for comment in comments.comments %}
                    <div>
                        <span class="commenter">{{ comment.user_id }}</span>
                        <span class="colon">:</span>
                        <span class="comment">{{ comment.comment }}</span> 
                    </div>
                {% endfor %}
                <span id="comment-length" length="{{ comments.length }}"></span>
            </div>
                {% if session.user.login_status %}
                <div class="comment-input">
                    {% csrf_token %}
                    <input id="new-comment" type="text" placeholder="comment anything ...">
                    <button id="comment-send-btn">Send</button>
                </div>
            {% endif %}
        </div>

        <script src="{% static 'js/common/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/app_cse_ps/project_booth_page.js' %}"></script>
    </body>
</html>

templates/app_cse_ps/project_registration_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/app_cse_ps/project_registration_page.css' %}">
        <title>Project Registration Page</title>
    </head>
    <body>

        {% include "../common/navbar.html" %}

        <h1 class="title">Project Registration</h1>
        <form action="{% url 'app_cse_ps:project_registration' %}" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<div class="project_title">
				<label for="project_title">Project Title: </label>
				<input type="text" name="project_title" id="project_title" required>
			</div>

			<div class="course-selection">

				<div class="course-name">
					<label for="course">Course: </label>
					<select name="course_name" id="course_name">
						<option value=""> Select Course </option>
					</select>
				</div>

				<div class="section-name">
					<label for="section">Section: </label>
					<select name="section" id="section">
						<option value=""> Select Section </option>
					</select>
				</div>

				
				<!-- <label for="course">Course: </label>
				<select name="course">
				{% for course in data %}
					<option value="{{ course.id }}">{{ course.course_code}} ({{ course.name }}) : {{ course.course_name }}</option>
				{% endfor %}
				</select> -->
			</div>


			<div class="short_description">
				<label for="short_description">Short Description: </label>
				<textarea name="short_description" rows="4" cols="80" required></textarea>
			</div>

			<div class="add_project_member">
				<label for="add_project_member">Enter Student ID to add new member: </label>
				<div class="input_controls">
					<input type="text" name="" id="student_id" placeholder="Student ID">
					{% comment %} <button type="button" name="check_student" id="check_student">Check</button> {% endcomment %}
					<p id="student_info"></p>
					<button class="add_disabled" type="button" name="add_member" id="add_member" disabled>Add Member</button>
				</div>
			</div>

			<div class="project_members">
				<label for="project_members">Student IDs of Project Members</label>
				<textarea name="project_members" rows="5" cols="80" readonly id="project_members"></textarea>
			</div>

			<input type="submit" value="Submit">

        </form>

        <script src="{% static 'js/common/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/app_cse_ps/project_registration_page.js' %}"></script>
    </body>
</html>