app_club_ff/urls.py
from django.conf import settings
from django.urls import path
from . import views

from django.shortcuts import render
from my_modules.base_views import DBAction, DBRead
from django.views.generic import TemplateView
from my_modules.database import MySql
from django.http import HttpResponse
import json

app_name = "app_club_ff"

urlpatterns = [
    path("index/", views.Index.as_view(), name="index"),
    path("fest_registration_page/",views.FestRegistrationPage.as_view(login_required=True), name="fest_registration_page"),
    path("fest_registration/", views.FestRegistration.as_view(login_required=True), name="fest_registration"),
    path("get_club_names/", views.get_club_names, name="get_club_names"),
    path("get_cff_years/", views.get_cff_years, name="get_cff_years"),
    path("get_filtered_cff/<club_name>/<year>", views.get_filtered_cff, name="get_filtered_cff"),
    path("fest_feed_page/", views.FestFeed.as_view(), name="fest_feed_page"),
    path("post_processor/<club_id>/<criteria>/<offset>/", views.PostProcessor.as_view(), name="post_processor"),
    path("archive_cff_booths_page/", views.ArchiveCffBooths.as_view(), name="archive_cff_booths_page"),
]

uiu_emas/urls.py
from django.contrib import admin
from django.urls import path, include
from app_cse_ps import urls as app_cse_ps_urls
from app_club_ff import urls as app_club_ff_urls
from app_admin import urls as app_admin_urls
from app_general import urls as app_general_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(app_admin_urls)),
    path('admin_django/', admin.site.urls),
    path('cse_ps/', include(app_cse_ps_urls), name="cse_ps"),
    path('club_ff/', include(app_club_ff_urls), name="club_ff"),
    path('general/', include(app_general_urls), name="general"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_club_ff/views.py
from django.shortcuts import render
from my_modules.base_views import DBAction
from django.views.generic import TemplateView

from django.shortcuts import render
from my_modules.base_views import DBAction, DBRead
from django.views.generic import TemplateView
from my_modules.database import MySql
from django.http import HttpResponse
import json


# Create your views here.

class Index(DBRead):
    template_name = "app_club_ff/index.html"


class FestRegistrationPage(DBRead):
    template_name = "app_club_ff/fest_registration_page.html"
    database = MySql.db()

    def get_context_data(self, request,  *args, **kwargs):
        context = {}
        student_id = request.session["user"]["id"]
        print(student_id)
        already_exist = self.database.query(f"SELECT * FROM cff_registrations WHERE student_id = '{student_id}'")
        if len(already_exist) != 0:
            self.template_name = "app_club_ff/fest_already_registered.html"
            return context

        student = self.database.query(
            f"SELECT student_id, name, uiu_email FROM students WHERE student_id = '{student_id}'")
        context["data"] = []
        list = ['student_id', 'name', 'uiu_email']
        for tup in student:
            context["data"].append({list[0]: tup[0], list[1]: tup[1], list[2]: tup[2]})
        return context


class FestRegistration(DBAction):
    def action(self, request, **kwargs):
        self.redirect_url = "app_club_ff:index"
        post_data = dict(**request.POST)
        print('YES')
        student_id = post_data["student_id"][0]
        club_id = post_data["club"][0]
        tshirt_size = post_data["tshirt_size"][0]

        self.database.query(
            f"INSERT INTO cff_registrations (student_id,club_id, t_shirt_size) VALUES ('{student_id}','{club_id}','{tshirt_size}')")
        return


def get_club_names(request):
    database = MySql.db()
    club_list = database.query("SELECT club_id, name FROM clubs")
    context = {}
    context["data"] = []
    list = ['club_id', 'club_name']
    for tup in club_list:
        context["data"].append({list[0]: tup[0], list[1]: tup[1]})
    context = json.dumps(context)
    return HttpResponse(context)


class FestFeed(DBRead):
    template_name = "app_club_ff/fest_feed_page.html"

    def get_context_data(self, request, *args, **kwargs):
        context = {}
        context["clubs"] = self.get_club_names()
        context["sorting_criterias"] = [
            {"value": "desc", "option": "Newest"},
            {"value": "asc", "option": "Oldest"}
        ]
        context["feed_posts"] = self.get_feed_posts()
        context["length"] = len(context["feed_posts"])
        return context

    def get_club_names(self):
        club_name = self.database.get("clubs")
        return club_name

    def get_feed_posts(self):
        feed_posts = self.database.get("feed_posts", other_clauses=[
            "order by time_created desc",
            "limit 5"
        ])

        for i in range(len(feed_posts)):
            club_name = self.database.get("clubs", ["name"], {"id": feed_posts[i]["club_id"]})[0]["name"]
            feed_posts[i]["club_name"] = club_name

        return feed_posts


class PostProcessor(DBRead):
    template_name = "app_club_ff/post_processor.html"

    def get_context_data(self, request, *args, **kwargs):
        context = {}

        offset = int(kwargs["offset"])
        club_id = kwargs["club_id"]
        criteria = kwargs["criteria"]

        context["feed_posts"] = self.get_feed_posts(offset, club_id, criteria)
        context["length"] = len(context["feed_posts"]) + offset
        return context

    def get_feed_posts(self, offset, club_id, criteria):
        conditions = None

        if club_id != "all":
            conditions = {
                "club_id": club_id
            }

        feed_posts = self.database.get("feed_posts", conditions=conditions, other_clauses=[
            f"order by time_created {criteria}",
            "limit 5",
            f"offset {offset}" if offset != -1 else "",
        ])

        for i in range(len(feed_posts)):
            club_name = self.database.get("clubs", ["name"], {"id": feed_posts[i]["club_id"]})[0]["name"]
            feed_posts[i]["club_name"] = club_name

        return feed_posts


def get_cff_years(request):
    database = MySql.db()
    years = database.query("SELECT DISTINCT year(time_created) FROM booths")
    context = {}
    context["data"] = []
    list = ['year']
    for tup in years:
        context["data"].append({list[0]: tup[0]})
    print(context["data"])
    context = json.dumps(context)
    return HttpResponse(context)


def get_filtered_cff(request, club_name, year):
    database = MySql.db()
    print(club_name)
    print(year)

    if club_name != 'NULL' and year == 'NULL':
        booths = database.query(
            f"SELECT booths.id, YEAR(booths.time_created), booths.club_id, booths.club_description, clubs.name FROM booths JOIN clubs ON booths.club_id = clubs.club_id WHERE booths.status = 1 and clubs.name = '{club_name}' ")
    elif year != 'NULL' and club_name == 'NULL':
        booths = database.query(
            f"SELECT booths.id, YEAR(booths.time_created), booths.club_id, booths.club_description, clubs.name FROM booths JOIN clubs ON booths.club_id = clubs.club_id WHERE booths.status = 1 and YEAR(booths.time_created) = '{year}' ")
    elif year != 'NULL' and club_name != 'NULL':
        booths = database.query(
            f"SELECT booths.id, YEAR(booths.time_created), booths.club_id, booths.club_description, clubs.name FROM booths JOIN clubs ON booths.club_id = clubs.club_id WHERE booths.status = 1 and YEAR(booths.time_created) = '{year}' and clubs.name = '{club_name}' ")
    elif club_name == 'NULL' and year == 'NULL':
        booths = database.query(
            f"SELECT booths.id, YEAR(booths.time_created), booths.club_id, booths.club_description, clubs.name FROM booths JOIN clubs ON booths.club_id = clubs.club_id WHERE booths.status = 1")

    context = {}
    context["data"] = []
    list = ['id', 'time_created', 'club_id', 'club_description', 'club_name']

    for tup in booths:
        club_name_tup = database.query(f"SELECT name FROM clubs WHERE id = {tup[2]}")
        club_name = club_name_tup[0]
        context["data"].append(
            {list[0]: tup[0], list[1]: tup[1], list[2]: tup[2], list[3]: tup[3], list[4]: club_name})
    print(context)
    context = json.dumps(context)
    return HttpResponse(context)


class ArchiveCffBooths(DBRead):
    template_name = "app_club_ff/archive_cff_booths_page.html"

    def get_context_data(self, request,  *args, **kwargs):
        context = {}
        booths = self.database.query(
            "SELECT id, time_created, club_id, club_description FROM booths WHERE `status` = 1")

        context["data"] = []
        list = ['id', 'time_created', 'club_id', 'club_description', 'club_name']

        for tup in booths:
            c_name = self.database.query(f"SELECT name FROM clubs WHERE id = {tup[2]}")
            c_name = c_name[0]
            context["data"].append(
                {list[0]: tup[0], list[1]: tup[1], list[2]: tup[2], list[3]: tup[3], list[4]: c_name[0]})
        return context

templates/app_club_ff/archive_cff_booths_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/app_club_ff/archive_cff_booths_page.css' %}">
        <title>Document</title>
    </head>
    <body>

        {% include "../common/navbar.html" %}

        <h1 class="title">UIU CLUB FORUM FEST ARCHIVE</h1>

        {% comment %} <h3 class="instructions"><i class="fad fa-asterisk"></i>Select a booth to view its content</h3> {% endcomment %}

        <div class="filter">
  				<select name="club_name_filter" id="club_name_filter">
                    <option value=""> Club Name </option>
  				</select>

  				<select name="year_filter" id="year_filter">
  					<option value=""> Year </option>
  				</select>

          <button type="button" name="filter" id="filter">Filter</button>
        </div>

        <br>
        <div class="booth_thumbnails" id = "booth_thumbnails">
            {% for club in data %}
                <div class="booth_thumbnail">
                    <div class="club_name">
                        <span>Club name: </span><span>{{ club.club_name }}</span>
                    </div>
                    <div class="club_description">
                        <span>Description: </span><span>{{ club.club_description }} </span>
                    </div>
                    <div class="time_created">
                        <span>Created at: </span><span>{{ club.time_created }}</span>
                    </div>

                    {% comment %} use this id, if needed {{project.id}} {% endcomment %}
                </div>
            {% endfor %}
        </div>

        <script src="{% static 'js/common/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/app_club_ff/cff_booth_archive_page.js' %}"></script>
    </body>
</html>

templates/app_club_ff/fest_already_registered.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/app_club_ff/fest_already_registered.css' %}">
        <title>Document</title>
    </head>
    <body>

        {% include "../common/navbar.html" %}

        <h1 class="title">You're already registered for the fest!!!</h1>

        <script src="{% static 'js/common/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/app_club_ff/fest_already_registered.js' %}"></script>
    </body>
</html>

templates/app_club_ff/fest_feed_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/app_club_ff/fest_feed_page.css' %}">
        <title>Document</title>
    </head>
    <body>
        
        {% include "common/navbar.html" %}
        <div class="title">Fest Feed</div>
        <div class="filters">
            <div class="filter">
                <label for="club_name">Club:</label>
                <select name="club_name" id="club_name">
                    <option value="all">ALL</option>
                    {% for club in clubs %}
                    <option value="{{club.club_id}}">{{club.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="filter">
                <label for="sort_by">Sort by:</label>
                <select name="sort_by" id="sort_by">
                    {% for sorting_criteria in sorting_criterias %}
                        <option value="{{ sorting_criteria.value }}">{{ sorting_criteria.option }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>

        <div class="feed">

            {% for feed_post in feed_posts %}
            <div class="post_card">
                <div class="header">
                    <h2><span>Posted by:</span><span>{{ feed_post.club_name }}</span></h2>
                    <h3><span>Posted at. </span><span>{{ feed_post.time_created }}</span></h3>
                </div>
                <h3>
                    {{ feed_post.caption }}
                </h3>
                <img src="{{ MEDIA_URL }}{{feed_post.image_path}}" alt="">
            </div>
            {% endfor %}

            <span id="posts_length" length="{{ length }}"></span>
                      
        </div>
        <button id="load-more">Load More</button>
        <script src="{% static 'js/common/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/app_club_ff/fest_feed_page.js' %}"></script>
    </body>
</html>

templates/app_club_ff/fest_registration_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="{% static 'fonts/font-awesome/css/all.css' %}">
		<link rel="stylesheet" href="{% static 'css/app_club_ff/fest_registration_page.css' %}">
		<title>Fest Registration Page</title>
	</head>
	<body>
		
		{% include "../common/navbar.html" %}

        <h1 class="title">Fest Registration</h1>

        <form action="{% url 'app_club_ff:fest_registration' %}" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{% for student in data %}
				<div>
					<label for="student_name">Name: </label>
					<input type="text" name="student_name" id="student_name" value="{{ student.name }}" readonly>
				</div>

				<div>
					<label for="student_id"> ID: </label>
					<input type="text" name="student_id" id="student_id" value="{{ student.student_id }}" readonly>
				</div>

				<div>
					<label for="student_email"> Email Address: </label>
					<input type="text" name="student_email" id="student_email" value="{{ student.uiu_email }}" readonly>
				</div>
			{% endfor %}

			<div class="club">
				<label for="club">Member of: </label>
				<select class="club" name="club" id="club" required>
					<option value="">Select Your Club</option>
				</select>
			</div>

			<div class="tshirt_size">
				<label for="tshirt_size"> T-shirt Size: </label>
				<select name="tshirt_size" id="tshirt_size">
					<option value="S"> S </option>
					<option value="M"> M </option>
					<option value="L"> L </option>
					<option value="XL"> XL </option>
					<option value="XXL"> XXL </option>
					<option value="XXXL"> XXXL </option>
				</select>
			</div>

			<input type="submit" value="Register">
        </form>
		
		<script src="{% static 'js/common/jquery-3.6.0.min.js' %}"></script>
		<script src="{% static 'js/app_club_ff/fest_registration_page.js' %}"></script>
	</body>
</html>

templates/app_club_ff/index.html
{% load static %}
<html>
    <head>
        <title>UIU Club Forum Fest</title>
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/app_club_ff/index.css' %}">
    </head>
    <body>
        
        {% include "../common/navbar.html" %}

        <h1 class="title">UIU Club Forum Fest</h1>
        
        <div class="options">
            <a href="{% url 'app_club_ff:fest_feed_page' %}">
                <i class="fad fa-rss"></i>
                <span>Fest Feed</span>
            </a>
            <a href="{% url 'app_club_ff:archive_cff_booths_page' %}">
                <i class="fad fa-archive"></i>
                <span>Archive</span>
            </a>
        </div>

    </body>
</html>

templates/app_club_ff/post_processor.html
{% for feed_post in feed_posts %}
<div class="post_card">
    <div class="header">
        <h2><span>Posted by:</span><span>{{ feed_post.club_name }}</span></h2>
        <h3><span>Posted at. </span><span>{{ feed_post.time_created }}</span></h3>
    </div>
    <h3>
        {{ feed_post.caption }}
    </h3>
    <img src="{{ MEDIA_URL }}{{feed_post.image_path}}" alt="">
</div>
{% endfor %}

{% if length != 0 %}
    <span id="posts_length" length="{{ length }}"></span>
{% endif %}